author: wysohn
name: RapidFramework
main: io.github.wysohn.rapidframework3.bukkit.plugin.FakePlugin
softdepend:
- ProtocolLib
- Vault
- PlaceholderAPI
- ProtocolLib
- WorldGuard
version: 3.5.15
commands:
  rapidframework:
    aliases:
    - rap
    description: description
authors: [
  ]
depend: [
  ]
permissions:
  rapidframework:
    description: Grant admin permission
api-version: '1.13'
