api-version: '1.13'
depend: [
  ]
author: wysohn
permissions:
  rapidframework4:
    description: Grant admin permission
name: RapidFramework4
main: io.github.wysohn.rapidframework4.bukkit.plugin.FakePlugin
softdepend:
- ProtocolLib
- Vault
- PlaceholderAPI
- ProtocolLib
- WorldGuard
version: 4.0.0
commands:
  rapidframework4:
    aliases:
    - rap
    description: description
authors: [
  ]
