author: wysohn
name: RapidFramework
main: io.github.wysohn.rapidframework2.bukkit.plugin.FakePlugin
softdepend:
- ProtocolLib
- Vault
- PlaceholderAPI
- ProtocolLib
- WorldGuard
version: 2.13.14
commands:
  rapidframework:
    aliases:
    - rap
    description: description
authors: [
  ]
depend: [
  ]
permissions:
  rapidframework:
    description: Grant admin permission
api-version: '1.13'
