api-version: '1.13'
depend: [
  ]
author: wysohn
permissions:
  rapidframework:
    description: Grant admin permission
name: RapidFramework
main: io.github.wysohn.rapidframework3.bukkit.plugin.FakePlugin
softdepend:
- ProtocolLib
- Vault
- PlaceholderAPI
- ProtocolLib
- WorldGuard
version: 3.16.2
commands:
  rapidframework:
    aliases:
    - rap
    description: description
authors: [
  ]
