author: wysohn
name: RapidFramework
main: io.github.wysohn.rapidframework2.bukkit.plugin.FakePlugin
softdepend:
  - ProtocolLib
  - Vault
  - PlaceholderAPI
  - UserInterfaceLib
  - JsonApi
  - TitleAPI
  - TTA
version: 2.8.0
commands:
  rapidframework:
    aliases:
      - rf
      - rframe
    description: some description
    permission: rapidframework.admin